name: Process FluSight Data

on: workflow_dispatch

jobs:
  process-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v3
      
    - name: Checkout FluSight-forecast-hub
      uses: actions/checkout@v3
      with:
        repository: 'cdcepi/FluSight-forecast-hub'
        path: 'FluSight-forecast-hub'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm
        
    - name: Process FluSight data
      run: |
        mkdir -p app/public/processed_data
        python scripts/process_flusight_data.py --hub-path ./FluSight-forecast-hub --output-path ./app/public/processed_data
        echo "Checking processed files:"
        ls -la app/public/processed_data/
        
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: processed-flusight-data
        path: app/public/processed_data/
        if-no-files-found: error
        retention-days: 1
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/public/processed_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed data")
        if [ $? -eq 1 ]; then
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push
        fi
      env:
        PAT: ${{ secrets.PAT }}

  build-and-deploy:
    needs: process-data
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
          
      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: processed-flusight-data
          path: app/public/processed_data
          
      - name: Install dependencies
        working-directory: ./app
        run: npm ci
        
      - name: Clean
        working-directory: ./app
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          
      - name: Build website
        working-directory: ./app
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./app/dist
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
